default: &default
  admin_credentials:
    username: 'test'
    password: 'test'

development:
  <<: *default
  shrine_secret_key: '18b070557af0a7b4fb21549f817b281f'

test:
  <<: *default
  shrine_secret_key: '9d13e2aa68b8b2ad2d3c9f9ebbf4fe04'

production:
  <<: *default
  admin_credentials:
    username: <%= ENV['ADMIN_USERNAME'] %>
    password: <%= ENV['ADMIN_PASSWORD'] %>
  shrine_secret_key: <%= ENV['SHRINE_SECRET_KEY'] %>
